### ISSUE TITLE
visual studio missing file

### ISSUE THREAD

**Issue by fmr999** [CSCI150Fall18Team5/NDetect#1]
I believe that the file NDetect.vcxproj is missing so can't compile project.

**Comment by Zckd78** [comment]
I'll see if I can get that uploaded today.

**Comment by Zckd78** [comment]
I uploaded the NDetect.vcxproj file in my latest commit. Go ahead and sync to get the latest code.

**Comment by fmr999** [comment]
Thanks, the project loads
