### ISSUE TITLE
error pcap_next_ex unresolved and more alike

### ISSUE THREAD

**Issue by fmr999** [CSCI150Fall18Team5/NDetect#2]
steps were taken so far 

Location for WinPcap
C++ General Additional Include Directories:
D:\WinPcap\WpdPack\Include

Linker General Additional Library Directories
D:\WinPcap\WpdPack\Lib

Linker Input Additional Dependencies
wpcap.lib Packet.lib

C++ Preprocessor
HAVE_REMOTE       WIN32          WPCAP

I don't know if I'm missing another configuration

**Comment by Zckd78** [comment]
Check that those folders actually contain the files, double check that you have the following includes and code in your pch.h file

`
#include <pcap.h>

#ifndef WIN32
#include <sys/socket.h>
#include <netinet/in.h>
#else
#include <winsock.h>
#endif
`

Otherwise, I can help you when we have school.

**Comment by Zckd78** [comment]
Try the suggestion from [this StackOverflow question](https://stackoverflow.com/questions/18982762/linker-errors-with-winpcap#19056738).

**Comment by fmr999** [comment]
Thanks, I solved the problem by changing the architecture from 64 bits to 32 bits under

Project -> Properties -> Platform -> Win32
