### ISSUE TITLE
bandwidth issues

### ISSUE THREAD

**Issue by rdanyali** [CSCI150Fall18Team5/NDetect#30]
have you merged the related filtering code to master branch??? I was wondering that I might need the filter class in order to calculate the total incoming and outgoing bandwidth. Am I make sense??

**Comment by fmr999** [comment]
yes, I included the Filter class in the main branch. you might want to create another class for stats and look at how the packets are being handled in the capture engine and also the DTO which contains the information about packets and its information.

**Comment by rdanyali** [comment]
ok cool. thanks a lot
