### ISSUE TITLE
opengl32.lib

### ISSUE THREAD

**Issue by rdanyali** [CSCI150Fall18Team5/NDetect#31]
I do not have this file in my NDetect folder, therefore I was not able to add opengl32.lib to my linker. without this file I will not be able to see GUI in my console ?? Am I doing it right?

**Comment by Zckd78** [comment]
The file itself isn't included in NDetect folder, it should be installed with Visual Studio. 
Try adding **opengl32.lib** to Linker > Input > Additional Dependencies.
Let me know if it compiles. After you select the interface, it another window with a circle and dots should appear.

**Comment by rdanyali** [comment]
oh ok. thanks a lot

**Comment by rdanyali** [comment]
Zack bro, after I fetched the master, I saw the graphic and filter .cpp and
.h files in visual studio, but I was not be able to compile it; it was
giving me the error "cannot find statistics file". when I click on the
right side of on statistics.cpp or .h file I was getting this error "object
reference not set to an instance of an object". I decide to exclude my
statistics file and then run it, which caused more errors. I hope I haven't
messed up the original code from the main branch. If I wasn't able to run
the program on my laptop, I will just make couple slides on powerpoint to
explain the progress and all other stuff from the wiki page, and I will ask
you guys to do the demo part, unless, we can fix the issue couple hours
prior to the class. I have no class after 11. I'm so sorry bro, its my
first time using both GitHub and visual studio. two years ago I just took
csci40 and 41 which everything basically was on paper and some small codes
on DEVC++ as far as I remember. Tomorrow after presentation I will talk to
Professor and tell him that I have not contributed enough even though I'm
trying my best. Is there anyways, that I can include the codes in
"statistics"  that I excluded from the project?? sorry bro, I'm still
trying to figure out what to do. please let the rest of the group members
know. I didn't want to put this message on GitHub.

**Comment by Zckd78** [comment]
As long as you don't commit your changes to master, you haven't messed up the master branch code. This semester has been a learning experience in terms of Github for me as well. Every time Fernando puts code in I have to fix something that broke, and same for him.
In response to your earlier comment, you'll have to find out which interface captures packets. If that's 1, then use 1 for testing.
You should see the GUI window when it starts capturing. If not, you need to open the GitHub program and Sync from Origin again to get the latest changes on master.
If we can't figure out the errors, I can demo on my laptop tomorrow while you and Ivan present. Please work with Ivan to put together a PowerPoint. List the features we have, and be ready to talk about what we've accomplished. Look at the Project tab here on Github to see what features we've finished. 
Our whole team will stand there for the presentation, as I saw other teams do the same last Milestone, but I expect you and Ivan to speak the most.

**Comment by rdanyali** [comment]
sure bro. thanks a lot

**Comment by Zckd78** [comment]
Closing this issue since we fixed your problem in class.
