### ISSUE TITLE
preparing presentation

### ISSUE THREAD

**Issue by rdanyali** [CSCI150Fall18Team5/NDetect#32]
Hey Ivan. Wanna meet at 12:30 to put stuff together?? feel free to call me 2092627264....

**Comment by ivanvasquez1967** [comment]
Yeah I'm working on it now. I have a meeting for Senior Design around 12 with advisior.

**Comment by rdanyali** [comment]
ok bro.. im at the library, and I will attend to the presentation of the first groups

**Comment by ivanvasquez1967** [comment]
I've been working on it on Google Drive.
I'll send you the link right now

**Comment by rdanyali** [comment]
cool , I started to include some stuff, feel free to delete them if you think they are unnecessary to be mentioned

**Comment by Zckd78** [comment]
Can either of you post the link here? If I end up driving the presentation, I'll need the PowerPoint as well.

**Comment by Zckd78** [comment]
Closing the thread since the Milestone presentation has passed.
