### ISSUE TITLE
Error on current master branch

### ISSUE THREAD

**Issue by fmr999** [CSCI150Fall18Team5/NDetect#7]
Severity    Code    Description    Project    File    Line    Suppression State
Error    LNK2019    unresolved external symbol impntohs@4 referenced in function "public: void __thiscall CaptureEngine::DecodePacket(void)" (?DecodePacket@CaptureEngine@@QAEXXZ)    NDetect    D:\CSCI\CSCI 150\CSCI150Project\NDetect\NDetect\CaptureEngine.obj    1

**Comment by Zckd78** [comment]
This is fixed in the Project Properties. Right click the Project, then select Properties.
From there: Linker > Input > Additional Dependencies: wpcap.lib Packet.lib **ws2_32.lib**
You and everyone in the team needs to add **ws2_32.lib** to that list.

**Comment by Zckd78** [comment]
Is this still an issue? If not, please close it.
